spring:
  datasource:
    url: jdbc:postgresql://43.203.3.27:5432/mydb?currentSchema=fooroduce
    username: myuser
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none  # 원하면 create, none 가능
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  logging:
    level:
      com.foodu: INFO
      ROOT: DEBUG

  web:
    cors:
      allowed-origin-patterns:
        - "https://*.fooroduce.7team.xyz"
        - "http://localhost:5173"
      allowed-methods:
        - GET
        - POST
        - PUT
      allowed-headers:
        - "Content-Type"
        - "Authorization"
      allow-credentials: true

kakao:
  client-id: 987871
  redirect-uri: https://fooroduce.7team.xyz/oauth/callback/kakao
  api-key: 053fe749d4f9c2cfafa4bf0958899ae1