#spring:
#  datasource:
#    url: ${DB_URL}
#    username: ${DB_USER}
#    password: ${DB_PASSWORD}
#    driver-class-name: ${DB_DRIVER}
#
#  jpa:
#    hibernate:
#      ddl-auto: none  # 원하면 create, none 가능
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        format_sql: true
#
#  logging:
#    level:
#      com.foodu: INFO
#      ROOT: DEBUG
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/fooroduce
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # 개발 중에는 update 또는 create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

logging:
  level:
    com.foodu: INFO
    ROOT: DEBUG


  web:
    cors:
      allowed-origin-patterns:
        - "https://*.fooroduce.7team.xyz"
        - "http://localhost:5173"
      allowed-methods:
        - GET
        - POST
        - PUT
      allowed-headers:
        - "Content-Type"
        - "Authorization"
      allow-credentials: true

kakao:
  client-id: 987871
  redirect-uri: https://fooroduce.7team.xyz/oauth/callback/kakao
  api-key: 053fe749d4f9c2cfafa4bf0958899ae1

cloud:
  aws:
    credentials:
      access-key: dummy
      secret-key: dummy
    region:
      static: ap-northeast-2
    s3:
      bucket: dummy


#cloud:
#  aws:
#    credentials:
#      access-key: ${CLOUD_AWS_CREDENTIALS_ACCESS_KEY}
#      secret-key: ${CLOUD_AWS_CREDENTIALS_SECRET_KEY}
#    region:
#      static: ${CLOUD_AWS_REGION_STATIC}
#    s3:
#      bucket: ${CLOUD_AWS_S3_BUCKET}