spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER_CLASS}

  jpa:
    hibernate:
      ddl-auto: none  # 원하면 create, none 가능
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  logging:
    level:
      com.foodu.myapp: INFO
      com.foodu.myapp.IDE.submission: DEBUG
